# This workflow builds the Java project with Maven

name: Java CI with Maven

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ] # Runs on pushes to the main branch
  pull_request:
    branches: [ "main" ] # Runs on pull requests targeting the main branch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job is named "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Sets up a Java 23 environment for the build
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin' # Adoptium Temurin is a popular OpenJDK distribution
          cache: 'maven' # Caches Maven dependencies to speed up subsequent builds

      # Step 3: Runs the Maven build command
      - name: Build with Maven
        run: mvn -B package --file pom.xml # -B runs in non-interactive (batch) mode